# Spectral decomposition

![Creative Commons License](https://i.creativecommons.org/l/by/4.0/88x31.png)  
This work by Jephian Lin is licensed under a [Creative Commons Attribution 4.0 International License](http://creativecommons.org/licenses/by/4.0/).

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits import mplot3d
from scipy import linalg as LA
import sympy

In [2]:
def spec_decom(A, tol=0.0001):
    n = A.shape[0]
    vals,vecs = LA.eigh(A)

    inds = np.where((vals[1:] - vals[:-1]) > tol)[0]
    starts = np.hstack([np.array([0]), inds+1])
    ends = np.hstack([inds+1, np.array([n])])

    dist_vals = vals[starts]
    projs = np.zeros((len(dist_vals), n, n))
    i = 0
    for s,e in zip(starts,ends):
        space = vecs[:,s:e]
        projs[i] = space.dot(space.T)
        i += 1

    return dist_vals, projs

## Main idea

A matrix $A$ is **symmetric** if $A^\top = A$.  

Every symmetric matrix $A$ can be written as  
$$ A = \sum_{i=1}^q \lambda_i P_i$$
such that $\sum_{i=1}^q P_i = I$, $P_iP_j = O$ if $i\neq j$, and $P_i^2 = P_i$.  
This is called the **spectral decomposition** of $A$.  

Each $P_i$ is in fact a projection matrix onto a space $E_i$.  
For any vector ${\bf v}$ in $E_i$, $A{\bf v} = \lambda_i{\bf v}$.  
We call $\lambda_i$ an **eigenvalue** ,  
call ${\bf v}$ an **eigenvector** ,  
and $E_i$ an **eigenspace** of $A$.

## Side stories

- eigenvalue, eigenvector, eigenspace
- spectral decomposition = projection then scale

## Experiments

###### Exercise 1
Let  
```python
A = np.ones((5,5), dtype=float) - np.eye(5, dtype=float)
v1 = np.ones((5,), dtype=float)
v2 = np.array([1,-1,0,0,0], dtype=float)
```

###### 1(a)
Check if ${\bf v}_1$ is an eigenvector of $A$.  
If yes, what is the eigenvalue?

In [24]:
### your answer here
def check_eigenvector(A, v):
    if np.allclose(v, 0):
        return False, None

    result = A @ v
    eigenvalue = result[0] / v[0]

    is_eigenvector = np.allclose(result, eigenvalue * v)

    if is_eigenvector:
        return True, eigenvalue
    else:
        return False, None

A = np.ones((5,5), dtype=float) - np.eye(5, dtype=float)
v1 = np.ones((5,), dtype=float)
v2 = np.array([1,-1,0,0,0], dtype=float)

check_eigenvector(A, v1)

(True, np.float64(4.0))

###### 1(b)
Check if the $i$-th entry of ${\bf v}_2$ is zero then the $i$-th entry of $A{\bf v}_2$ is also zero.  

In [33]:
import numpy as np

A = np.ones((5,5), dtype=float) - np.eye(5, dtype=float)

for i in range(len(v2)):
    v2 = np.array([1,-1,0,0,0], dtype=float)
    v2[i] = 0
    Av2 = A @ v2
    print(f"Iteration i={i}: v2 = {v2}, Av2 = {Av2}")

Iteration i=0: v2 = [ 0. -1.  0.  0.  0.], Av2 = [-1.  0. -1. -1. -1.]
Iteration i=1: v2 = [1. 0. 0. 0. 0.], Av2 = [0. 1. 1. 1. 1.]
Iteration i=2: v2 = [ 1. -1.  0.  0.  0.], Av2 = [-1.  1.  0.  0.  0.]
Iteration i=3: v2 = [ 1. -1.  0.  0.  0.], Av2 = [-1.  1.  0.  0.  0.]
Iteration i=4: v2 = [ 1. -1.  0.  0.  0.], Av2 = [-1.  1.  0.  0.  0.]


###### 1(c)
Check if ${\bf v}_2$ is an eigenvector of $A$.  
If yes, what is the eigenvalue?

In [26]:
### your answer here
def check_eigenvector(A, v):
    if np.allclose(v, 0):
        return False, None

    result = A @ v
    eigenvalue = result[0] / v[0]

    is_eigenvector = np.allclose(result, eigenvalue * v)

    if is_eigenvector:
        return True, eigenvalue
    else:
        return False, None

A = np.ones((5,5), dtype=float) - np.eye(5, dtype=float)
v1 = np.ones((5,), dtype=float)
v2 = np.array([1,-1,0,0,0], dtype=float)

check_eigenvector(A, v2)

(True, np.float64(-1.0))

###### Exercise 2
Let  
```python
A = np.array([[2,-1,-1],
              [-1,2,-1],
              [-1,-1,2]]) / 3
v1 = np.array([1,1,1])
v2 = np.array([1,-1,0])
```
Since checking the zero is tiring, we will use a different approach to test whether a vector is an eigenvector.  
The following are equivalent:  
- $A{\bf v} = \lambda{\bf v}$ for some $\lambda$
- $A{\bf v}$ is a multiple of ${\bf v}$
- $A{\bf v}$ and ${\bf v}$ are parallel (zero vectors are considered to be parallel to any vector)
- $|\langle A{\bf v}, {\bf v}\rangle| = \|A{\bf v}\|\|{\bf v}\|$

###### 2(a)
Compute $|\langle A{\bf v}_1, {\bf v}_1\rangle|$ and $\|A{\bf v}_1\|\|{\bf v}_1\|$.  
Then see if they are close.

In [37]:
### your answer here
A = np.array([[2,-1,-1],
              [-1,2,-1],
              [-1,-1,2]]) / 3
v1 = np.array([1,1,1])
v2 = np.array([1,-1,0])

Av1 = A @ v1

abs_inner_product = np.abs(np.dot(Av1, v1))

norm_product = np.linalg.norm(Av1) * np.linalg.norm(v1)

print(f"|⟨Av1, v1⟩| = {abs_inner_product}")
print(f"||Av1||*||v1||   = {norm_product}")
print(f"Are they close? {np.isclose(abs_inner_product, norm_product)}")

|⟨Av1, v1⟩| = 0.0
||Av1||*||v1||   = 0.0
Are they close? True


###### 2(b)
Do the same for ${\bf v}_2$.

In [38]:
### your answer here
### your answer here
A = np.array([[2,-1,-1],
              [-1,2,-1],
              [-1,-1,2]]) / 3
v1 = np.array([1,1,1])
v2 = np.array([1,-1,0])

Av2 = A @ v2

abs_inner_product = np.abs(np.dot(Av2, v2))

norm_product = np.linalg.norm(Av2) * np.linalg.norm(v2)

print(f"|⟨Av2, v2⟩| = {abs_inner_product}")
print(f"||Av2||*||v2||   = {norm_product}")
print(f"Are they close? {np.isclose(abs_inner_product, norm_product)}")

|⟨Av2, v2⟩| = 2.0
||Av2||*||v2||   = 2.0000000000000004
Are they close? True


###### 2(c)
Run and understand the code below.  

```python
%matplotlib notebook

tol = 0.1
vs = 5*np.random.randn(3,10000)
Avs = A.dot(vs)
dots = np.abs(np.sum(vs * Avs, axis = 0)) ### |<Avi, vi>|'s
Avs_length = np.linalg.norm(Avs, axis=0) ### ||Avi||'s
vs_length = np.linalg.norm(vs, axis=0) ### ||vi||'s
diff = np.abs( dots - Avs_length*vs_length)
mask = (diff < tol) ### mask for potential eigenvectors
eigvecs = vs[:,mask]

ax = plt.axes(projection='3d')
ax.set_xlim(-5,5)
ax.set_ylim(-5,5)
ax.set_zlim(-5,5)
ax.scatter(eigvecs[0], eigvecs[1], eigvecs[2])
```
What is the plane in the output?  
Change `tol` to 1 or 2.  Then you will see a vague straight line appears.  Why?

In [41]:
### your answer here
%matplotlib notebook

tol = 0.1
vs = 5*np.random.randn(3,10000)
Avs = A.dot(vs)
dots = np.abs(np.sum(vs * Avs, axis = 0)) ### |<Avi, vi>|'s
Avs_length = np.linalg.norm(Avs, axis=0) ### ||Avi||'s
vs_length = np.linalg.norm(vs, axis=0) ### ||vi||'s
diff = np.abs( dots - Avs_length*vs_length)
mask = (diff < tol) ### mask for potential eigenvectors
eigvecs = vs[:,mask]

ax = plt.axes(projection='3d')
ax.set_xlim(-5,5)
ax.set_ylim(-5,5)
ax.set_zlim(-5,5)
ax.scatter(eigvecs[0], eigvecs[1], eigvecs[2])

## Exercises

###### Exercise 3
Let  
```python
A = np.array([[0,1,0,0,0,1],
              [1,0,1,0,0,0],
              [0,1,0,1,0,0],
              [0,0,1,0,1,0],
              [0,0,0,1,0,1],
              [1,0,0,0,1,0]])
vals,projs = spec_decom(A)
```
Here `vals` are all the $\lambda_i$'s and `projs` are all the $P_i$'s.  

###### 3(a)
Check if $A = \sum_{i=0}^3\lambda_iP_i$.  
Can you do it without any for loop?  
Note:  You might need `np.set_printoptions(precision=1, suppress=True)`.

In [42]:
### your answer here
A = np.array([[0,1,0,0,0,1],
              [1,0,1,0,0,0],
              [0,1,0,1,0,0],
              [0,0,1,0,1,0],
              [0,0,0,1,0,1],
              [1,0,0,0,1,0]])
vals,projs = spec_decom(A)

np.set_printoptions(precision=1, suppress=True)
A_reconstructed = np.tensordot(vals, projs, axes=1)
print(A_reconstructed)

[[-0.  1.  0.  0.  0.  1.]
 [ 1.  0.  1.  0. -0.  0.]
 [ 0.  1.  0.  1.  0. -0.]
 [ 0.  0.  1. -0.  1.  0.]
 [ 0. -0.  0.  1.  0.  1.]
 [ 1.  0. -0.  0.  1.  0.]]


###### 3(b)
Let  
```python
v = np.ones((6,))
```
Check if $A{\bf v} = \sum_{i=0}^3 \lambda_i P_i{\bf v}$.

In [45]:
### your answer here
A = np.array([[0,1,0,0,0,1],
              [1,0,1,0,0,0],
              [0,1,0,1,0,0],
              [0,0,1,0,1,0],
              [0,0,0,1,0,1],
              [1,0,0,0,1,0]])
vals,projs = spec_decom(A)
v = np.ones((6,))

np.set_printoptions(precision=1, suppress=True)
A_reconstructed = np.tensordot(vals, projs@v, axes=1)
print(A_reconstructed)

A@v

[2. 2. 2. 2. 2. 2.]


array([2., 2., 2., 2., 2., 2.])

###### 3(c)
Pick any $0\leq i,j\leq 3$.  
Check if $P_iP_j = O$.

In [11]:
### your answer here


###### 3(d)
Pick any $0\leq i\leq 3$.  
Check if $P_i^2 = P_i$.

In [12]:
### your answer here

##### Exercise 4
Let  
```python
%matplotlib inline
plt.axis('equal')
A = np.array([[2,1],
              [1,2]])
t = np.linspace(0, 2*np.pi, 36)
xs = np.cos(t)
ys = np.sin(t)
vs = np.vstack([xs, ys])
Avs = A.dot(vs)
```

###### 4(a)
Plot a red point at the origin.  
Plot the points (columns) in `vs` using `c=t` .  
Then plot the points (columns) in `Avs` using `c=t` .  
Interpret the output using the spectral decomposition.

In [13]:
### your answer here

###### 4(b)
Do the same with  
```python
A = np.array([[1,1],
              [1,1]])
```

In [14]:
### your answer here

##### Exercise 5
Let  
```python
A = np.array([[0,1,0,0,0,1],
              [1,0,1,0,0,0],
              [0,1,0,1,0,0],
              [0,0,1,0,1,0],
              [0,0,0,1,0,1],
              [1,0,0,0,1,0]])
vals,projs = spec_decom(A)

k = 3
```

###### 5(a)
Let  
```python
B = k*A
vals_B,projs_B = spec_decom(B)
```
Find a relation between `vals` and `vals_B` using `k` .  
Find a relation between `projs` and `projs_B` .

In [15]:
### your answer here

###### 5(b)
Let  
```python
B = A + k*np.eye(6)
vals_B,projs_B = spec_decom(B)
```
Find a relation between `vals` and `vals_B` using `k` .  
Find a relation between `projs` and `projs_B` .

In [16]:
### your answer here

###### 5(c)
It looks like $\lambda=1$ is an eigenvalue of $A$.  
Use `sympy.Matrix` to find the null space of $A - \lambda I$.  
Find a projection matrix of it, and compare it with the corresponding projection matrix in `projs` .

In [17]:
### your answer here